#!/bin/bash

if hostname | grep -q black
then
    #echo black
    #get the i3 config file
    cp -u ~/.config/i3/config ./i3conflaptop

    #get the polybar config file
    cp -u ~/.config/polybar/config ./polybarconflaptop

    #get bashrc
    cp -u ~/.bashrc ./bashrclaptop

    #get vimrc
    cp -u ~/.vimrc ./vimrc
elif hostname | grep -q arcgap
then
    #echo arcgap
    #get the i3 config file
    cp -u ~/.config/i3/config ./i3confarch

    #get the polybar config file
    cp -u ~/.config/polybar/config ./polybarconfarch

    #get bashrc
    cp -u ~/.bashrc ./bashrcarch

    #get .Xresources
    cp -u ~/.Xresources ./Xresourcesarch

    #get alacritty config
    cp -u ~/.config/alacritty/alacritty.yml ./alacrittyarch.yml

    #get picom
    cp -u ~/.config/picom.conf ./picomarch

    #get vimrc
    cp -u ~/.vimrc ./vimrc

    #get muttrc
    cp -u ~/.neomuttrc ./neomuttrc
else
    #echo mountains
    #get the i3 config file
    cp -u ~/.config/i3/config ./i3conf

    #get the polybar config file
    cp -u ~/.config/polybar/config ./polybarconf

    #get bashrc
    cp -u ~/.bashrc ./bashrc

    #get .Xresources
    cp -u ~/.Xresources ./Xresources

    #get alacritty config
    cp -u ~/.config/alacritty/alacritty.yml ./alacritty.yml

    #get vimrc
    cp -u ~/.vimrc ./vimrc

    #get muttrc
    cp -u ~/.neomuttrc ./neomuttrc
fi
