#!/bin/bash

if hostname | grep -q black
then
    #echo black
    #get the i3 config file
    sudo cp ~/.config/i3/config ./i3conflaptop

    #get the polybar config file
    sudo cp ~/.config/polybar/config ./polybarconflaptop

    #get bashrc
    sudo cp ~/.bashrc ./bashrclaptop

    #get vimrc
    sudo cp ~/.vimrc ./vimrc
elif hostname | grep -q arcgap
then
    #echo arcgap
    #get the i3 config file
    sudo cp ~/.config/i3/config ./i3confarch

    #get the polybar config file
    sudo cp ~/.config/polybar/config ./polybarconfarch

    #get bashrc
    sudo cp ~/.bashrc ./bashrcarch

    #get .Xresources
    sudo cp ~/.Xresources ./Xresourcesarch

    #get vimrc
    sudo cp ~/.vimrc ./vimrc
else
    #echo mountains
    #get the i3 config file
    sudo cp ~/.config/i3/config ./i3conf

    #get the polybar config file
    sudo cp ~/.config/polybar/config ./polybarconf

    #get bashrc
    sudo cp ~/.bashrc ./bashrc

    #get vimrc
    sudo cp ~/.vimrc ./vimrc
fi
