#!/bin/bash

if hostname | grep -q black
then
    #echo black
    #get the i3 config file
    cp ~/.config/i3/config ./i3conflaptop

    #get the polybar config file
    cp ~/.config/polybar/config ./polybarconflaptop

    #get bashrc
    cp ~/.bashrc ./bashrclaptop

    #get vimrc
    cp ~/.vimrc ./vimrc
elif hostname | grep -q arcgap
then
    #echo arcgap
    #get the i3 config file
    cp ~/.config/i3/config ./i3confarch

    #get the polybar config file
    cp ~/.config/polybar/config ./polybarconfarch

    #get bashrc
    cp ~/.bashrc ./bashrcarch

    #get .Xresources
    cp ~/.Xresources ./Xresourcesarch

    #get alacritty config
    cp ~/.config/alacritty/alacritty.yml ./alacrittyarch.yml

    #get picom
    cp ~/.config/picom.conf ./picomarch

    #get vimrc
    cp ~/.vimrc ./vimrc
else
    #echo mountains
    #get the i3 config file
    cp ~/.config/i3/config ./i3conf

    #get the polybar config file
    cp ~/.config/polybar/config ./polybarconf

    #get bashrc
    cp ~/.bashrc ./bashrc

    #get alacritty config
    cp ~/.config/alacritty/alacritty.yml ./alacritty.yml

    #get vimrc
    cp ~/.vimrc ./vimrc
fi
