#!/bin/bash

if hostname | grep -q black
then
    #echo black
    cp -u ./i3conflaptop ~/.config/i3/config

    cp -u ./polybarconflaptop ~/.config/polybar/config

    cp ./bashrclaptop ~/.bashrc

    cp -u ./vimrc ~/.vimrc
elif hostname | grep -q arcgap
then
    #echo arcgap
    cp -u ./i3confarch ~/.config/i3/config

    sudo cp -u ./polybarconfarch ~/.config/polybar/config

    cp -u ./bashrcarch ~/.bashrc

    cp -u ./Xresourcesarch ~/.Xresources

    cp -u ./alacrittyarch.yml ~/.config/alacritty/alacritty.yml

    cp -u ./picomarch ~/.config/picom.conf

    cp -u ./vimrc ~/.vimrc

    cp -u ./neomuttrc ~/.neomuttrc
else
    #echo mountains
    cp -u ./i3conf ~/.config/i3/config

    cp -u ./polybarconf ~/.config/polybar/config

    cp -u ./bashrc ~/.bashrc

    cp -u ./Xresources ~/.Xresources

    cp -u ./alacritty.yml ~/.config/alacritty/alacritty.yml

    cp -u ./vimrc ~/.vimrc

    cp -ur ./doom.d/ ~/.doom.d/

    cp -u ./neomuttrc ~/.neomuttrc
fi

