#!/usr/bin/env bash

if hostname | grep -q black
then
    #echo black
    cp -u ./i3conflaptop ~/.config/i3/config

    cp -u ./polybarconflaptop ~/.config/polybar/config

    cp ./bashrclaptop ~/.bashrc

    cp -u ./vimrc ~/.vimrc
elif hostname | grep -q arcgap
then
    #echo arcgap
    cp -u ./i3confarch ~/.config/i3/config

    sudo cp -u ./polybarconfarch ~/.config/polybar/config

    cp -u ./bashrcarch ~/.bashrc

    cp -u ./Xresourcesarch ~/.Xresources

    cp -u ./alacrittyarch.yml ~/.config/alacritty/alacritty.yml

    cp -u ./picomarch ~/.config/picom.conf

    cp -u ./vimrc ~/.vimrc

    cp -u ./qutebrowser ~/.config/qutebrowser/config.py

    cp -u ./neomuttrc ~/.neomuttrc
elif hostname | grep -q nixtop
then
    #echo nixtop
    cp -u ./i3confnix ~/.config/i3/config

    sudo cp -u ./polybarconfnix ~/.config/polybar/config

    cp -u ./bashrcnix ~/.bashrc

    cp -u ./alacrittynix.yml ~/.config/alacritty/alacritty.yml

    cp -u ./vimrcnix ~/.vimrc

    cp -u ./configuration.nix /etc/nixos/configuration.nix
elif hostname | grep -q portastation
then
    #echo portastation
    cp -u ./configport.fish ~/.config/fish/config.fish

    cp -u ./alacrittyport.yml ~/.config/alacritty/alacritty.yml

    cp -u ./initport.lua ~/.config/nvim/init.lua
else
    #echo mountains
    cp -u ./i3conf ~/.config/i3/config

    cp -u ./polybarconf ~/.config/polybar/config

    cp -u ./bashrc ~/.bashrc

    cp -u ./Xresources ~/.Xresources

    cp -u ./alacritty.yml ~/.config/alacritty/alacritty.yml

    cp -u ./vimrc ~/.vimrc

    cp -u ./qutebrowser ~/.config/qutebrowser/config.py

    cp -u ./neomuttrc ~/.neomuttrc
fi

