#!/bin/bash

if hostname | grep -q black
then
    #echo black
    sudo cp ./i3conflaptop ~/.config/i3/config

    sudo cp ./polybarconflaptop ~/.config/polybar/config

    sudo cp ./bashrclaptop ~/.bashrc

    sudo cp ./vimrc ~/.vimrc
elif hostname | grep -q arcgap
then
    #echo arcgap
    sudo cp ./i3confarch ~/.config/i3/config

    sudo cp ./polybarconfarch ~/.config/polybar/config

    sudo cp ./bashrcarch ~/.bashrc

    sudo cp ./Xresourcesarch ~/.Xresources

    sudo cp ./picomarch ~/.config/picom.conf

    sudo cp ./vimrc ~/.vimrc
else
    #echo mountains
    sudo cp ./i3conf ~/.config/i3/config

    sudo cp ./polybarconf ~/.config/polybar/config

    sudo cp ./bashrc ~/.bashrc

    sudo cp ./vimrc ~/.vimrc
fi

